# Generated by Django 5.1.7 on 2025-04-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MemoTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(max_length=255)),
                ("reference_data", models.CharField(max_length=50)),
                ("month", models.CharField(max_length=50)),
                ("year", models.CharField(max_length=50)),
                ("recent", models.BooleanField(default=True)),
                ("file", models.FileField(upload_to="pdf/")),
            ],
        ),
    ]
