# Generated by Django 5.1.7 on 2025-04-13 11:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="memotable",
            table="memo_table",
        ),
    ]
