# Generated by Django 5.2 on 2025-05-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2_dep_model", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="first_name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adminuser",
            name="last_name",
            field=models.CharField(default="John", max_length=20),
            preserve_default=False,
        ),
    ]
