# Generated by Django 5.2 on 2025-11-29 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("b2_dep_model", "0002_adminuser_first_name_adminuser_last_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memotable",
            options={
                "ordering": ["-month"],
                "verbose_name": "Memo",
                "verbose_name_plural": "Memo",
            },
        ),
        migrations.AddField(
            model_name="memotable",
            name="created_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the nemo was lasted updated"
            ),
        ),
        migrations.AddField(
            model_name="memotable",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="When the memo was lasted updated"
            ),
        ),
        migrations.AlterField(
            model_name="memotable",
            name="description",
            field=models.TextField(
                help_text="Detailed description of the memo", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="memotable",
            name="file",
            field=models.FileField(
                help_text="PDF file only, max 10MB",
                upload_to="pdf/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="memotable",
            name="month",
            field=models.CharField(
                db_index=True, help_text="Month of the memo", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="memotable",
            name="recent",
            field=models.BooleanField(
                db_index=True, default=True, help_text="Recent memo"
            ),
        ),
        migrations.AlterField(
            model_name="memotable",
            name="reference_data",
            field=models.CharField(
                db_index=True,
                help_text="Reference data (max 50 characters)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="memotable",
            name="title",
            field=models.CharField(
                help_text="Memo title (max 25 characters)", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="memotable",
            name="year",
            field=models.CharField(
                db_index=True, help_text="Year of the memo", max_length=50
            ),
        ),
        migrations.AddIndex(
            model_name="memotable",
            index=models.Index(
                fields=["month", "year"], name="memo_table_month_902771_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memotable",
            index=models.Index(
                fields=["recent", "-created_at"], name="memo_table_recent_4a09be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memotable",
            index=models.Index(fields=["title"], name="memo_table_title_472ff9_idx"),
        ),
    ]
